
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 工作步骤
    steps:
      # 检查
      - name: Checkout
        uses: actions/checkout@v2

      # 初始化环境
      - name: Initialization environment
        run: |
          sudo -E apt-get update
          sudo mkdir -p /workdir

      # 下载源码
      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone https://source.codeaurora.org/external/imx/linux-imx -b  v5.4.98 linux-imx
          git clone https://source.codeaurora.org/external/imx/uboot-imx -b imx_v2020.04_5.4.70_2.3.0 uboot-imx
          
      # 压缩源码
      #- name: uzip source code
       # run: |
