name: download linux-imx


on:
  #push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 工作步骤
    steps:
      # 检查
      - name: Checkout
        uses: actions/checkout@main

      - name: Space cleanup
        run: |
          sudo -E apt-get update

      # 下载源码
      - name: Clone source code
        run: 
          git clone https://source.codeaurora.org/external/imx/linux-imx -b  v5.4.98 linux-imx
          
      # 压缩源码
      - name: uzip source code
        run: |
          zip -r linux_imx.zip linux-imx
          mkdir file
          cp linux_imx.zip ./file
          cd file

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt
          path: file/
